### ISSUE TITLE
Kernel::getPHPDIContainer() should be protected not private

### ISSUE THREAD

**Issue by jasonbouffard** [PHP-DI/Symfony-Bridge#17]
Our PHP-DI container is already built before Symfony's Kernel boots. So in our AppKernel we'd like to override `Kernel::getPHPDIContainer()` to provide our built PHP-DI container to the `SymfonyContainerBridge` vs having to run through a `ContainerBuilder`. Any objections to this?

No BC break required.

**Comment by mnapoli** [comment]
Makes sense go for it!

**Comment by jasonbouffard** [comment]
Awesome. Thanks for the fast response. PR is up. Think we can get a 2.0.1 release quickly? Or 2.1.0?

**Comment by mnapoli** [comment]
Done! I think that's a record for me, thanks for the quick PR too ;)

**Comment by jasonbouffard** [comment]
Thank you!
